[modules.barge-dev]
source = "."
entrypoint = true

[modules.dagger-go-sdk]
source = "github.com/dagger/go-sdk"

[modules.go]
source = "github.com/frantjc/daggerverse/go#dagger-v1"

[modules.mise]
source = "github.com/frantjc/daggerverse/mise#dagger-v1"

[modules.trivy]
source = "github.com/frantjc/daggerverse/trivy#dagger-v1"

[modules.dagger-go-sdk.as-sdk]
name = "go"

[[modules.dagger-go-sdk.as-sdk.modules]]
path = "."
