name = "barge-dev"
engineVersion = "v0.21.7"
source = ".dagger"

[runtime]
  source = "go"

[[dependencies]]
  name = "go"
  source = "github.com/frantjc/daggerverse/go@dagger-v1"
  pin = "9eaa49457dbb0653d491f2ec89b26aa94257d41e"

[[dependencies]]
  name = "kwok"
  source = "github.com/frantjc/daggerverse/kwok@dagger-v1"
  pin = "9eaa49457dbb0653d491f2ec89b26aa94257d41e"

[[dependencies]]
  name = "mise"
  source = "github.com/frantjc/daggerverse/mise@dagger-v1"
  pin = "9eaa49457dbb0653d491f2ec89b26aa94257d41e"

[[dependencies]]
  name = "release"
  source = "github.com/frantjc/daggerverse/release@dagger-v1"
  pin = "9eaa49457dbb0653d491f2ec89b26aa94257d41e"

[[dependencies]]
  name = "wolfi"
  source = "github.com/dagger/dagger/modules/wolfi@v0.21.7"
  pin = "054f94b2d86c0ac00bef11ac4550816973c4aeef"

[[clients]]
  generator = "go"
  directory = "./internal/dagger"
