// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type BargeDev struct { // barge-dev (../../../:0:0)
	query *querybuilder.Selection

	id      *ID
	release *Void
	test    *Void
}

func (r *BargeDev) WithGraphQLQuery(q *querybuilder.Selection) *BargeDev {
	return &BargeDev{
		query: q,
	}
}

// BargeDevBinaryOpts contains options for BargeDev.Binary
type BargeDevBinaryOpts struct {

	// Default: "v0.0.0-unknown"
	Version string

	Goarch string

	Goos string
}

func (r *BargeDev) Binary(workspace *Workspace, opts ...BargeDevBinaryOpts) *File {
	assertNotNil("workspace", workspace)
	q := r.query.Select("binary")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `goarch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goarch) {
			q = q.Arg("goarch", opts[i].Goarch)
		}
		// `goos` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goos) {
			q = q.Arg("goos", opts[i].Goos)
		}
	}
	q = q.Arg("workspace", workspace)

	return &File{
		query: q,
	}
}

// A unique identifier for this BargeDev.
func (r *BargeDev) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *BargeDev) XXX_GraphQLType() string {
	return "BargeDev"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *BargeDev) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *BargeDev) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *BargeDev) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *BargeDev) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = BargeDev{query: selectNode(dag.query, id, "BargeDev")}
	return nil
}

func (r *BargeDev) Release(ctx context.Context, workspace *Workspace, githubRepo string, githubToken *Secret) error {
	assertNotNil("workspace", workspace)
	assertNotNil("githubToken", githubToken)
	if r.release != nil {
		return nil
	}
	q := r.query.Select("release")
	q = q.Arg("workspace", workspace)
	q = q.Arg("githubRepo", githubRepo)
	q = q.Arg("githubToken", githubToken)

	return q.Execute(ctx)
}

// BargeDevTestOpts contains options for BargeDev.Test
type BargeDevTestOpts struct {
	GithubToken *Secret

	GithubRepo string

	AcrName string

	AzureConfig *Directory
}

func (r *BargeDev) Test(ctx context.Context, workspace *Workspace, opts ...BargeDevTestOpts) error {
	assertNotNil("workspace", workspace)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
		// `githubRepo` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubRepo) {
			q = q.Arg("githubRepo", opts[i].GithubRepo)
		}
		// `acrName` optional argument
		if !querybuilder.IsZeroValue(opts[i].AcrName) {
			q = q.Arg("acrName", opts[i].AcrName)
		}
		// `azureConfig` optional argument
		if !querybuilder.IsZeroValue(opts[i].AzureConfig) {
			q = q.Arg("azureConfig", opts[i].AzureConfig)
		}
	}
	q = q.Arg("workspace", workspace)

	return q.Execute(ctx)
}

func (r *Query) BargeDev() *BargeDev { // barge-dev (../../../:0:0)
	q := r.query.Select("bargeDev")

	return &BargeDev{
		query: q,
	}
}
