// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type BargeDev struct { // barge-dev (../../.dagger/main.go:14:6)
	query *querybuilder.Selection

	id      *ID
	release *Void
	test    *Void
}

func (r *BargeDev) WithGraphQLQuery(q *querybuilder.Selection) *BargeDev {
	return &BargeDev{
		query: q,
	}
}

// BargeDevBinaryOpts contains options for BargeDev.Binary
type BargeDevBinaryOpts struct {
	Ws *Workspace // barge-dev (../../.dagger/main.go:80:2)

	// Default: "v0.0.0-unknown"
	Version string // barge-dev (../../.dagger/main.go:82:2)

	Goarch string // barge-dev (../../.dagger/main.go:84:2)

	Goos string // barge-dev (../../.dagger/main.go:86:2)
}

func (r *BargeDev) Binary(opts ...BargeDevBinaryOpts) *File { // barge-dev (../../.dagger/main.go:78:1)
	q := r.query.Select("binary")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `goarch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goarch) {
			q = q.Arg("goarch", opts[i].Goarch)
		}
		// `goos` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goos) {
			q = q.Arg("goos", opts[i].Goos)
		}
	}

	return &File{
		query: q,
	}
}

// A unique identifier for this BargeDev.
func (r *BargeDev) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *BargeDev) XXX_GraphQLType() string {
	return "BargeDev"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *BargeDev) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *BargeDev) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *BargeDev) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// BargeDevReleaseOpts contains options for BargeDev.Release
type BargeDevReleaseOpts struct {
	Ws *Workspace // barge-dev (../../.dagger/main.go:118:2)

	// Default: "frantjc/barge"
	GithubRepo string // barge-dev (../../.dagger/main.go:122:2)

	Brew bool // barge-dev (../../.dagger/main.go:124:2)
}

func (r *BargeDev) Release(ctx context.Context, githubToken *Secret, opts ...BargeDevReleaseOpts) error { // barge-dev (../../.dagger/main.go:116:1)
	assertNotNil("githubToken", githubToken)
	if r.release != nil {
		return nil
	}
	q := r.query.Select("release")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
		// `githubRepo` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubRepo) {
			q = q.Arg("githubRepo", opts[i].GithubRepo)
		}
		// `brew` optional argument
		if !querybuilder.IsZeroValue(opts[i].Brew) {
			q = q.Arg("brew", opts[i].Brew)
		}
	}
	q = q.Arg("githubToken", githubToken)

	return q.Execute(ctx)
}

// BargeDevTestOpts contains options for BargeDev.Test
type BargeDevTestOpts struct {
	Ws *Workspace // barge-dev (../../.dagger/main.go:19:2)

	GithubToken *Secret // barge-dev (../../.dagger/main.go:21:2)

	GithubRepo string // barge-dev (../../.dagger/main.go:23:2)

	AcrName string // barge-dev (../../.dagger/main.go:25:2)

	AzureConfig *Directory // barge-dev (../../.dagger/main.go:27:2)
}

func (r *BargeDev) Test(ctx context.Context, opts ...BargeDevTestOpts) error { // barge-dev (../../.dagger/main.go:17:1)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
		// `githubRepo` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubRepo) {
			q = q.Arg("githubRepo", opts[i].GithubRepo)
		}
		// `acrName` optional argument
		if !querybuilder.IsZeroValue(opts[i].AcrName) {
			q = q.Arg("acrName", opts[i].AcrName)
		}
		// `azureConfig` optional argument
		if !querybuilder.IsZeroValue(opts[i].AzureConfig) {
			q = q.Arg("azureConfig", opts[i].AzureConfig)
		}
	}

	return q.Execute(ctx)
}

// AsNode returns this BargeDev as a Node.
// This is a local type conversion — no GraphQL call.
func (r *BargeDev) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Retrieve the binding value, as type BargeDev
func (r *Binding) AsBargeDev() *BargeDev { // barge-dev (../../.dagger/main.go:14:6)
	q := r.query.Select("asBargeDev")

	return &BargeDev{
		query: q,
	}
}

// Create or update a binding of type BargeDev in the environment
func (r *Env) WithBargeDevInput(name string, value *BargeDev, description string) *Env { // barge-dev (../../.dagger/main.go:14:6)
	assertNotNil("value", value)
	q := r.query.Select("withBargeDevInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired BargeDev output to be assigned in the environment
func (r *Env) WithBargeDevOutput(name string, description string) *Env { // barge-dev (../../.dagger/main.go:14:6)
	q := r.query.Select("withBargeDevOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// BinaryOpts contains options for Query.Binary
type BinaryOpts struct {
	Ws *Workspace // barge-dev (../../.dagger/main.go:80:2)

	// Default: "v0.0.0-unknown"
	Version string // barge-dev (../../.dagger/main.go:82:2)

	Goarch string // barge-dev (../../.dagger/main.go:84:2)

	Goos string // barge-dev (../../.dagger/main.go:86:2)
}

func (r *Query) Binary(opts ...BinaryOpts) *File { // barge-dev (../../.dagger/main.go:78:1)
	q := r.query.Select("binary")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `goarch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goarch) {
			q = q.Arg("goarch", opts[i].Goarch)
		}
		// `goos` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goos) {
			q = q.Arg("goos", opts[i].Goos)
		}
	}

	return &File{
		query: q,
	}
}

// ReleaseOpts contains options for Query.Release
type ReleaseOpts struct {
	Ws *Workspace // barge-dev (../../.dagger/main.go:118:2)

	// Default: "frantjc/barge"
	GithubRepo string // barge-dev (../../.dagger/main.go:122:2)

	Brew bool // barge-dev (../../.dagger/main.go:124:2)
}

func (r *Query) Release(ctx context.Context, githubToken *Secret, opts ...ReleaseOpts) error { // barge-dev (../../.dagger/main.go:116:1)
	assertNotNil("githubToken", githubToken)
	q := r.query.Select("release")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
		// `githubRepo` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubRepo) {
			q = q.Arg("githubRepo", opts[i].GithubRepo)
		}
		// `brew` optional argument
		if !querybuilder.IsZeroValue(opts[i].Brew) {
			q = q.Arg("brew", opts[i].Brew)
		}
	}
	q = q.Arg("githubToken", githubToken)

	return q.Execute(ctx)
}

// TestOpts contains options for Query.Test
type TestOpts struct {
	Ws *Workspace // barge-dev (../../.dagger/main.go:19:2)

	GithubToken *Secret // barge-dev (../../.dagger/main.go:21:2)

	GithubRepo string // barge-dev (../../.dagger/main.go:23:2)

	AcrName string // barge-dev (../../.dagger/main.go:25:2)

	AzureConfig *Directory // barge-dev (../../.dagger/main.go:27:2)
}

func (r *Query) Test(ctx context.Context, opts ...TestOpts) error { // barge-dev (../../.dagger/main.go:17:1)
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
		// `githubToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubToken) {
			q = q.Arg("githubToken", opts[i].GithubToken)
		}
		// `githubRepo` optional argument
		if !querybuilder.IsZeroValue(opts[i].GithubRepo) {
			q = q.Arg("githubRepo", opts[i].GithubRepo)
		}
		// `acrName` optional argument
		if !querybuilder.IsZeroValue(opts[i].AcrName) {
			q = q.Arg("acrName", opts[i].AcrName)
		}
		// `azureConfig` optional argument
		if !querybuilder.IsZeroValue(opts[i].AzureConfig) {
			q = q.Arg("azureConfig", opts[i].AzureConfig)
		}
	}

	return q.Execute(ctx)
}
