// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Gh
func (r *Binding) AsGh() *Gh { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L10)
	q := r.query.Select("asGh")

	return &Gh{
		query: q,
	}
}

// Retrieve the binding value, as type GhRelease
func (r *Binding) AsGhRelease() *GhRelease { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L30)
	q := r.query.Select("asGhRelease")

	return &GhRelease{
		query: q,
	}
}

// Create or update a binding of type Gh in the environment
func (r *Env) WithGhInput(name string, value *Gh, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L10)
	assertNotNil("value", value)
	q := r.query.Select("withGhInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Gh output to be assigned in the environment
func (r *Env) WithGhOutput(name string, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L10)
	q := r.query.Select("withGhOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type GhRelease in the environment
func (r *Env) WithGhReleaseInput(name string, value *GhRelease, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L30)
	assertNotNil("value", value)
	q := r.query.Select("withGhReleaseInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GhRelease output to be assigned in the environment
func (r *Env) WithGhReleaseOutput(name string, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L30)
	q := r.query.Select("withGhReleaseOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Gh struct { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L10)
	query *querybuilder.Selection

	id          *ID
	setSecret   *Void
	setVariable *Void
}

func (r *Gh) WithGraphQLQuery(q *querybuilder.Selection) *Gh {
	return &Gh{
		query: q,
	}
}

func (r *Gh) Container() *Container { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L11)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Gh.
func (r *Gh) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Gh) XXX_GraphQLType() string {
	return "Gh"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Gh) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Gh) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Gh) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *Gh) Release(repo string, tag string) *GhRelease { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L39)
	q := r.query.Select("release")
	q = q.Arg("repo", repo)
	q = q.Arg("tag", tag)

	return &GhRelease{
		query: q,
	}
}

// GhSetSecretOpts contains options for Gh.SetSecret
type GhSetSecretOpts struct {
	App string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L182)

	Env string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L184)

	Org string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L186)

	Visibility string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L188)

	User bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L190)

	NoReposSelected bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L192)

	Repo []string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L194)
}

func (r *Gh) SetSecret(ctx context.Context, name string, body *Secret, opts ...GhSetSecretOpts) error { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L177)
	assertNotNil("body", body)
	if r.setSecret != nil {
		return nil
	}
	q := r.query.Select("setSecret")
	for i := len(opts) - 1; i >= 0; i-- {
		// `app` optional argument
		if !querybuilder.IsZeroValue(opts[i].App) {
			q = q.Arg("app", opts[i].App)
		}
		// `env` optional argument
		if !querybuilder.IsZeroValue(opts[i].Env) {
			q = q.Arg("env", opts[i].Env)
		}
		// `org` optional argument
		if !querybuilder.IsZeroValue(opts[i].Org) {
			q = q.Arg("org", opts[i].Org)
		}
		// `visibility` optional argument
		if !querybuilder.IsZeroValue(opts[i].Visibility) {
			q = q.Arg("visibility", opts[i].Visibility)
		}
		// `user` optional argument
		if !querybuilder.IsZeroValue(opts[i].User) {
			q = q.Arg("user", opts[i].User)
		}
		// `noReposSelected` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoReposSelected) {
			q = q.Arg("noReposSelected", opts[i].NoReposSelected)
		}
		// `repo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repo) {
			q = q.Arg("repo", opts[i].Repo)
		}
	}
	q = q.Arg("name", name)
	q = q.Arg("body", body)

	return q.Execute(ctx)
}

// GhSetVariableOpts contains options for Gh.SetVariable
type GhSetVariableOpts struct {
	Env string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L204)

	Org string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L206)

	Visibility string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L208)

	Repo []string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L210)
}

func (r *Gh) SetVariable(ctx context.Context, name string, body *Secret, opts ...GhSetVariableOpts) error { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L199)
	assertNotNil("body", body)
	if r.setVariable != nil {
		return nil
	}
	q := r.query.Select("setVariable")
	for i := len(opts) - 1; i >= 0; i-- {
		// `env` optional argument
		if !querybuilder.IsZeroValue(opts[i].Env) {
			q = q.Arg("env", opts[i].Env)
		}
		// `org` optional argument
		if !querybuilder.IsZeroValue(opts[i].Org) {
			q = q.Arg("org", opts[i].Org)
		}
		// `visibility` optional argument
		if !querybuilder.IsZeroValue(opts[i].Visibility) {
			q = q.Arg("visibility", opts[i].Visibility)
		}
		// `repo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repo) {
			q = q.Arg("repo", opts[i].Repo)
		}
	}
	q = q.Arg("name", name)
	q = q.Arg("body", body)

	return q.Execute(ctx)
}

// AsNode returns this Gh as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Gh) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type GhRelease struct { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L30)
	query *querybuilder.Selection

	create *Void
	edit   *Void
	id     *ID
	upload *Void
}

func (r *GhRelease) WithGraphQLQuery(q *querybuilder.Selection) *GhRelease {
	return &GhRelease{
		query: q,
	}
}

// GhReleaseCreateOpts contains options for GhRelease.Create
type GhReleaseCreateOpts struct {
	Title string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L46)

	GenerateNotes bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L48)

	Latest bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L50)

	Prerelease bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L52)

	Draft bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L54)

	VerifyTag bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L56)
}

func (r *GhRelease) Create(ctx context.Context, opts ...GhReleaseCreateOpts) error { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L43)
	if r.create != nil {
		return nil
	}
	q := r.query.Select("create")
	for i := len(opts) - 1; i >= 0; i-- {
		// `title` optional argument
		if !querybuilder.IsZeroValue(opts[i].Title) {
			q = q.Arg("title", opts[i].Title)
		}
		// `generateNotes` optional argument
		if !querybuilder.IsZeroValue(opts[i].GenerateNotes) {
			q = q.Arg("generateNotes", opts[i].GenerateNotes)
		}
		// `latest` optional argument
		if !querybuilder.IsZeroValue(opts[i].Latest) {
			q = q.Arg("latest", opts[i].Latest)
		}
		// `prerelease` optional argument
		if !querybuilder.IsZeroValue(opts[i].Prerelease) {
			q = q.Arg("prerelease", opts[i].Prerelease)
		}
		// `draft` optional argument
		if !querybuilder.IsZeroValue(opts[i].Draft) {
			q = q.Arg("draft", opts[i].Draft)
		}
		// `verifyTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].VerifyTag) {
			q = q.Arg("verifyTag", opts[i].VerifyTag)
		}
	}

	return q.Execute(ctx)
}

// GhReleaseEditOpts contains options for GhRelease.Edit
type GhReleaseEditOpts struct {
	Title string // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L90)

	GenerateNotes bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L92)

	Latest bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L94)

	Prerelease bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L96)

	Draft bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L98)

	VerifyTag bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L100)
}

func (r *GhRelease) Edit(ctx context.Context, opts ...GhReleaseEditOpts) error { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L87)
	if r.edit != nil {
		return nil
	}
	q := r.query.Select("edit")
	for i := len(opts) - 1; i >= 0; i-- {
		// `title` optional argument
		if !querybuilder.IsZeroValue(opts[i].Title) {
			q = q.Arg("title", opts[i].Title)
		}
		// `generateNotes` optional argument
		if !querybuilder.IsZeroValue(opts[i].GenerateNotes) {
			q = q.Arg("generateNotes", opts[i].GenerateNotes)
		}
		// `latest` optional argument
		if !querybuilder.IsZeroValue(opts[i].Latest) {
			q = q.Arg("latest", opts[i].Latest)
		}
		// `prerelease` optional argument
		if !querybuilder.IsZeroValue(opts[i].Prerelease) {
			q = q.Arg("prerelease", opts[i].Prerelease)
		}
		// `draft` optional argument
		if !querybuilder.IsZeroValue(opts[i].Draft) {
			q = q.Arg("draft", opts[i].Draft)
		}
		// `verifyTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].VerifyTag) {
			q = q.Arg("verifyTag", opts[i].VerifyTag)
		}
	}

	return q.Execute(ctx)
}

// A unique identifier for this GhRelease.
func (r *GhRelease) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GhRelease) XXX_GraphQLType() string {
	return "GhRelease"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GhRelease) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GhRelease) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GhRelease) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// GhReleaseUploadOpts contains options for GhRelease.Upload
type GhReleaseUploadOpts struct {
	Clobber bool // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L135)
}

func (r *GhRelease) Upload(ctx context.Context, assets []*File, opts ...GhReleaseUploadOpts) error { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L131)
	if r.upload != nil {
		return nil
	}
	q := r.query.Select("upload")
	for i := len(opts) - 1; i >= 0; i-- {
		// `clobber` optional argument
		if !querybuilder.IsZeroValue(opts[i].Clobber) {
			q = q.Arg("clobber", opts[i].Clobber)
		}
	}
	q = q.Arg("assets", assets)

	return q.Execute(ctx)
}

// AsNode returns this GhRelease as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GhRelease) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GhOpts contains options for Query.Gh
type GhOpts struct {
	Container *Container // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L17)
}

func (r *Query) Gh(githubToken *Secret, opts ...GhOpts) *Gh { // gh (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/gh/main.go#L14)
	assertNotNil("githubToken", githubToken)
	q := r.query.Select("gh")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}
	q = q.Arg("githubToken", githubToken)

	return &Gh{
		query: q,
	}
}
