// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Gh
func (r *Binding) AsGh() *Gh { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L12)
	q := r.query.Select("asGh")

	return &Gh{
		query: q,
	}
}

// Retrieve the binding value, as type GhRelease
func (r *Binding) AsGhRelease() *GhRelease { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L32)
	q := r.query.Select("asGhRelease")

	return &GhRelease{
		query: q,
	}
}

// Retrieve the binding value, as type GhReleaseAsset
func (r *Binding) AsGhReleaseAsset() *GhReleaseAsset { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L229)
	q := r.query.Select("asGhReleaseAsset")

	return &GhReleaseAsset{
		query: q,
	}
}

// Create or update a binding of type Gh in the environment
func (r *Env) WithGhInput(name string, value *Gh, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L12)
	assertNotNil("value", value)
	q := r.query.Select("withGhInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Gh output to be assigned in the environment
func (r *Env) WithGhOutput(name string, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L12)
	q := r.query.Select("withGhOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type GhReleaseAsset in the environment
func (r *Env) WithGhReleaseAssetInput(name string, value *GhReleaseAsset, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L229)
	assertNotNil("value", value)
	q := r.query.Select("withGhReleaseAssetInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GhReleaseAsset output to be assigned in the environment
func (r *Env) WithGhReleaseAssetOutput(name string, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L229)
	q := r.query.Select("withGhReleaseAssetOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type GhRelease in the environment
func (r *Env) WithGhReleaseInput(name string, value *GhRelease, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L32)
	assertNotNil("value", value)
	q := r.query.Select("withGhReleaseInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired GhRelease output to be assigned in the environment
func (r *Env) WithGhReleaseOutput(name string, description string) *Env { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L32)
	q := r.query.Select("withGhReleaseOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Gh struct { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L12)
	query *querybuilder.Selection

	id *ID
}

func (r *Gh) WithGraphQLQuery(q *querybuilder.Selection) *Gh {
	return &Gh{
		query: q,
	}
}

func (r *Gh) Container() *Container { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L13)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Gh.
func (r *Gh) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Gh) XXX_GraphQLType() string {
	return "Gh"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Gh) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Gh) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Gh) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *Gh) Release(repo string, tag string) *GhRelease { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L41)
	q := r.query.Select("release")
	q = q.Arg("repo", repo)
	q = q.Arg("tag", tag)

	return &GhRelease{
		query: q,
	}
}

// AsNode returns this Gh as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Gh) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type GhRelease struct { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L32)
	query *querybuilder.Selection

	create *Void
	edit   *Void
	id     *ID
	upload *Void
}

func (r *GhRelease) WithGraphQLQuery(q *querybuilder.Selection) *GhRelease {
	return &GhRelease{
		query: q,
	}
}

func (r *GhRelease) Assets(ctx context.Context) ([]GhReleaseAsset, error) { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L164)
	q := r.query.Select("assets")

	q = q.Select("id")

	type assets struct {
		Id ID
	}

	convert := func(fields []assets) []GhReleaseAsset {
		out := []GhReleaseAsset{}

		for i := range fields {
			val := GhReleaseAsset{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "GhReleaseAsset")
			out = append(out, val)
		}

		return out
	}
	var response []assets

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

// GhReleaseCreateOpts contains options for GhRelease.Create
type GhReleaseCreateOpts struct {
	Title string // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L48)

	GenerateNotes bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L50)

	Latest bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L52)

	Prerelease bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L54)

	Draft bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L56)

	VerifyTag bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L58)
}

func (r *GhRelease) Create(ctx context.Context, opts ...GhReleaseCreateOpts) error { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L45)
	if r.create != nil {
		return nil
	}
	q := r.query.Select("create")
	for i := len(opts) - 1; i >= 0; i-- {
		// `title` optional argument
		if !querybuilder.IsZeroValue(opts[i].Title) {
			q = q.Arg("title", opts[i].Title)
		}
		// `generateNotes` optional argument
		if !querybuilder.IsZeroValue(opts[i].GenerateNotes) {
			q = q.Arg("generateNotes", opts[i].GenerateNotes)
		}
		// `latest` optional argument
		if !querybuilder.IsZeroValue(opts[i].Latest) {
			q = q.Arg("latest", opts[i].Latest)
		}
		// `prerelease` optional argument
		if !querybuilder.IsZeroValue(opts[i].Prerelease) {
			q = q.Arg("prerelease", opts[i].Prerelease)
		}
		// `draft` optional argument
		if !querybuilder.IsZeroValue(opts[i].Draft) {
			q = q.Arg("draft", opts[i].Draft)
		}
		// `verifyTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].VerifyTag) {
			q = q.Arg("verifyTag", opts[i].VerifyTag)
		}
	}

	return q.Execute(ctx)
}

// GhReleaseDownloadOpts contains options for GhRelease.Download
type GhReleaseDownloadOpts struct {
	Archive string // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L194)
}

func (r *GhRelease) Download(pattern []string, opts ...GhReleaseDownloadOpts) *Directory { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L190)
	q := r.query.Select("download")
	for i := len(opts) - 1; i >= 0; i-- {
		// `archive` optional argument
		if !querybuilder.IsZeroValue(opts[i].Archive) {
			q = q.Arg("archive", opts[i].Archive)
		}
	}
	q = q.Arg("pattern", pattern)

	return &Directory{
		query: q,
	}
}

// GhReleaseEditOpts contains options for GhRelease.Edit
type GhReleaseEditOpts struct {
	Title string // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L92)

	GenerateNotes bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L94)

	Latest bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L96)

	Prerelease bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L98)

	Draft bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L100)

	VerifyTag bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L102)
}

func (r *GhRelease) Edit(ctx context.Context, opts ...GhReleaseEditOpts) error { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L89)
	if r.edit != nil {
		return nil
	}
	q := r.query.Select("edit")
	for i := len(opts) - 1; i >= 0; i-- {
		// `title` optional argument
		if !querybuilder.IsZeroValue(opts[i].Title) {
			q = q.Arg("title", opts[i].Title)
		}
		// `generateNotes` optional argument
		if !querybuilder.IsZeroValue(opts[i].GenerateNotes) {
			q = q.Arg("generateNotes", opts[i].GenerateNotes)
		}
		// `latest` optional argument
		if !querybuilder.IsZeroValue(opts[i].Latest) {
			q = q.Arg("latest", opts[i].Latest)
		}
		// `prerelease` optional argument
		if !querybuilder.IsZeroValue(opts[i].Prerelease) {
			q = q.Arg("prerelease", opts[i].Prerelease)
		}
		// `draft` optional argument
		if !querybuilder.IsZeroValue(opts[i].Draft) {
			q = q.Arg("draft", opts[i].Draft)
		}
		// `verifyTag` optional argument
		if !querybuilder.IsZeroValue(opts[i].VerifyTag) {
			q = q.Arg("verifyTag", opts[i].VerifyTag)
		}
	}

	return q.Execute(ctx)
}

// A unique identifier for this GhRelease.
func (r *GhRelease) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GhRelease) XXX_GraphQLType() string {
	return "GhRelease"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GhRelease) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GhRelease) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GhRelease) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// GhReleaseUploadOpts contains options for GhRelease.Upload
type GhReleaseUploadOpts struct {
	Clobber bool // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L137)
}

func (r *GhRelease) Upload(ctx context.Context, assets []*File, opts ...GhReleaseUploadOpts) error { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L133)
	if r.upload != nil {
		return nil
	}
	q := r.query.Select("upload")
	for i := len(opts) - 1; i >= 0; i-- {
		// `clobber` optional argument
		if !querybuilder.IsZeroValue(opts[i].Clobber) {
			q = q.Arg("clobber", opts[i].Clobber)
		}
	}
	q = q.Arg("assets", assets)

	return q.Execute(ctx)
}

// AsNode returns this GhRelease as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GhRelease) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type GhReleaseAsset struct { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L229)
	query *querybuilder.Selection

	digest *string
	id     *ID
	name   *string
	url    *string
}

func (r *GhReleaseAsset) WithGraphQLQuery(q *querybuilder.Selection) *GhReleaseAsset {
	return &GhReleaseAsset{
		query: q,
	}
}

func (r *GhReleaseAsset) Digest(ctx context.Context) (string, error) { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L233)
	if r.digest != nil {
		return *r.digest, nil
	}
	q := r.query.Select("digest")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *GhReleaseAsset) File() *File { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L237)
	q := r.query.Select("file")

	return &File{
		query: q,
	}
}

// A unique identifier for this GhReleaseAsset.
func (r *GhReleaseAsset) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *GhReleaseAsset) XXX_GraphQLType() string {
	return "GhReleaseAsset"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *GhReleaseAsset) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *GhReleaseAsset) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *GhReleaseAsset) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *GhReleaseAsset) Name(ctx context.Context) (string, error) { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L232)
	if r.name != nil {
		return *r.name, nil
	}
	q := r.query.Select("name")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *GhReleaseAsset) URL(ctx context.Context) (string, error) { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L234)
	if r.url != nil {
		return *r.url, nil
	}
	q := r.query.Select("url")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this GhReleaseAsset as a Node.
// This is a local type conversion — no GraphQL call.
func (r *GhReleaseAsset) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GhOpts contains options for Query.Gh
type GhOpts struct {
	Container *Container // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L19)
}

func (r *Query) Gh(githubToken *Secret, opts ...GhOpts) *Gh { // gh (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/gh/main.go#L16)
	assertNotNil("githubToken", githubToken)
	q := r.query.Select("gh")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}
	q = q.Arg("githubToken", githubToken)

	return &Gh{
		query: q,
	}
}
