// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Go
func (r *Binding) AsGo() *Go { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L13)
	q := r.query.Select("asGo")

	return &Go{
		query: q,
	}
}

// Create or update a binding of type Go in the environment
func (r *Env) WithGoInput(name string, value *Go, description string) *Env { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L13)
	assertNotNil("value", value)
	q := r.query.Select("withGoInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Go output to be assigned in the environment
func (r *Env) WithGoOutput(name string, description string) *Env { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L13)
	q := r.query.Select("withGoOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Go struct { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L13)
	query *querybuilder.Selection

	id          *ID
	staticcheck *Void
	test        *Void
	vet         *Void
	vulncheck   *Void
}

func (r *Go) WithGraphQLQuery(q *querybuilder.Selection) *Go {
	return &Go{
		query: q,
	}
}

// GoBuildOpts contains options for Go.Build
type GoBuildOpts struct {

	// Default: "./"
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L113)

	// Default: "-s -w"
	Ldflags string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L116)

	Cgo bool // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L118)

	Goarch string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L120)

	Goos string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L122)
}

func (r *Go) Build(opts ...GoBuildOpts) *File { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L109)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `ldflags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ldflags) {
			q = q.Arg("ldflags", opts[i].Ldflags)
		}
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `goarch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goarch) {
			q = q.Arg("goarch", opts[i].Goarch)
		}
		// `goos` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goos) {
			q = q.Arg("goos", opts[i].Goos)
		}
	}

	return &File{
		query: q,
	}
}

func (r *Go) Container() *Container { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L14)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// GoFmtOpts contains options for Go.Fmt
type GoFmtOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L194)
}

func (r *Go) Fmt(opts ...GoFmtOpts) *Changeset { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L191)
	q := r.query.Select("fmt")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return &Changeset{
		query: q,
	}
}

// GoGenerateOpts contains options for Go.Generate
type GoGenerateOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L265)
}

func (r *Go) Generate(opts ...GoGenerateOpts) *Changeset { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L262)
	q := r.query.Select("generate")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Go.
func (r *Go) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Go) XXX_GraphQLType() string {
	return "Go"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Go) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Go) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Go) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// GoStaticcheckOpts contains options for Go.Staticcheck
type GoStaticcheckOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L237)

	// Default: "latest"
	Version string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L240)
}

func (r *Go) Staticcheck(ctx context.Context, opts ...GoStaticcheckOpts) error { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L233)
	if r.staticcheck != nil {
		return nil
	}
	q := r.query.Select("staticcheck")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return q.Execute(ctx)
}

// GoTestOpts contains options for Go.Test
type GoTestOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L160)

	Race bool // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L162)

	Cgo bool // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L164)

	Tags []string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L166)
}

func (r *Go) Test(ctx context.Context, opts ...GoTestOpts) error { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L156)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `race` optional argument
		if !querybuilder.IsZeroValue(opts[i].Race) {
			q = q.Arg("race", opts[i].Race)
		}
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `tags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tags) {
			q = q.Arg("tags", opts[i].Tags)
		}
	}

	return q.Execute(ctx)
}

// GoTidyOpts contains options for Go.Tidy
type GoTidyOpts struct {

	// Default: "."
	Path string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L253)
}

func (r *Go) Tidy(opts ...GoTidyOpts) *Changeset { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L250)
	q := r.query.Select("tidy")
	for i := len(opts) - 1; i >= 0; i-- {
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
	}

	return &Changeset{
		query: q,
	}
}

// GoVetOpts contains options for Go.Vet
type GoVetOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L224)
}

func (r *Go) Vet(ctx context.Context, opts ...GoVetOpts) error { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L220)
	if r.vet != nil {
		return nil
	}
	q := r.query.Select("vet")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return q.Execute(ctx)
}

// GoVulncheckOpts contains options for Go.Vulncheck
type GoVulncheckOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L207)

	// Default: "latest"
	Version string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L210)
}

func (r *Go) Vulncheck(ctx context.Context, opts ...GoVulncheckOpts) error { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L203)
	if r.vulncheck != nil {
		return nil
	}
	q := r.query.Select("vulncheck")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return q.Execute(ctx)
}

// AsNode returns this Go as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Go) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GoOpts contains options for Query.Go
type GoOpts struct {
	Ws *Workspace // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L19)

	Exclude []string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L21)

	Gitignore bool // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L23)

	// Default: "."
	Path string // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L26)

	Container *Container // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L28)
}

func (r *Query) Go(opts ...GoOpts) *Go { // go (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/go/main.go#L17)
	q := r.query.Select("go")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
		// `exclude` optional argument
		if !querybuilder.IsZeroValue(opts[i].Exclude) {
			q = q.Arg("exclude", opts[i].Exclude)
		}
		// `gitignore` optional argument
		if !querybuilder.IsZeroValue(opts[i].Gitignore) {
			q = q.Arg("gitignore", opts[i].Gitignore)
		}
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Go{
		query: q,
	}
}
