// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Homebrew
func (r *Binding) AsHomebrew() *Homebrew { // homebrew (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/homebrew/main.go#L18)
	q := r.query.Select("asHomebrew")

	return &Homebrew{
		query: q,
	}
}

// Create or update a binding of type Homebrew in the environment
func (r *Env) WithHomebrewInput(name string, value *Homebrew, description string) *Env { // homebrew (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/homebrew/main.go#L18)
	assertNotNil("value", value)
	q := r.query.Select("withHomebrewInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Homebrew output to be assigned in the environment
func (r *Env) WithHomebrewOutput(name string, description string) *Env { // homebrew (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/homebrew/main.go#L18)
	q := r.query.Select("withHomebrewOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Homebrew struct { // homebrew (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/homebrew/main.go#L18)
	query *querybuilder.Selection

	cask *Void
	id   *ID
}

func (r *Homebrew) WithGraphQLQuery(q *querybuilder.Selection) *Homebrew {
	return &Homebrew{
		query: q,
	}
}

// HomebrewCaskOpts contains options for Homebrew.Cask
type HomebrewCaskOpts struct {
	Container *Container // homebrew (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/homebrew/main.go#L48)
}

// Cask renders a Homebrew cask formula for the given GitHub release and
// uploads it to the org's homebrew-tap repo, at Casks/<name>.rb, creating or
// updating the file as needed. Name, homepage and description are looked up
// from the repo.
func (r *Homebrew) Cask(ctx context.Context, githubToken *Secret, githubRepo string, tag string, opts ...HomebrewCaskOpts) error { // homebrew (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/homebrew/main.go#L42)
	assertNotNil("githubToken", githubToken)
	if r.cask != nil {
		return nil
	}
	q := r.query.Select("cask")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}
	q = q.Arg("githubToken", githubToken)
	q = q.Arg("githubRepo", githubRepo)
	q = q.Arg("tag", tag)

	return q.Execute(ctx)
}

// A unique identifier for this Homebrew.
func (r *Homebrew) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Homebrew) XXX_GraphQLType() string {
	return "Homebrew"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Homebrew) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Homebrew) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Homebrew) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// AsNode returns this Homebrew as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Homebrew) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

func (r *Query) Homebrew() *Homebrew { // homebrew (https://github.com/frantjc/daggerverse/tree/e91bca30db6fdae3ef6460d9e225d9138effe839/homebrew/main.go#L18)
	q := r.query.Select("homebrew")

	return &Homebrew{
		query: q,
	}
}
