// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Kwok
func (r *Binding) AsKwok() *Kwok { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L16)
	q := r.query.Select("asKwok")

	return &Kwok{
		query: q,
	}
}

// Retrieve the binding value, as type KwokCluster
func (r *Binding) AsKwokCluster() *KwokCluster { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L218)
	q := r.query.Select("asKwokCluster")

	return &KwokCluster{
		query: q,
	}
}

// Create or update a binding of type KwokCluster in the environment
func (r *Env) WithKwokClusterInput(name string, value *KwokCluster, description string) *Env { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L218)
	assertNotNil("value", value)
	q := r.query.Select("withKwokClusterInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired KwokCluster output to be assigned in the environment
func (r *Env) WithKwokClusterOutput(name string, description string) *Env { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L218)
	q := r.query.Select("withKwokClusterOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Kwok in the environment
func (r *Env) WithKwokInput(name string, value *Kwok, description string) *Env { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L16)
	assertNotNil("value", value)
	q := r.query.Select("withKwokInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Kwok output to be assigned in the environment
func (r *Env) WithKwokOutput(name string, description string) *Env { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L16)
	q := r.query.Select("withKwokOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Kwok struct { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L16)
	query *querybuilder.Selection

	id *ID
}

func (r *Kwok) WithGraphQLQuery(q *querybuilder.Selection) *Kwok {
	return &Kwok{
		query: q,
	}
}

// KwokClusterOpts contains options for Kwok.Cluster
type KwokClusterOpts struct {
	Container *Container // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L59)

	Components []string // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L61)

	ControllerPort int // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L63)

	Disable []string // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L65)

	DisableQpslimits bool // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L67)

	Enable []string // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L69)

	EnableCrds []string // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L71)

	// Default: 8080
	KubeApiserverInsecurePort int // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L74)

	KubeAuditPolicy *File // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L76)

	Etcd *File // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L78)

	Jaeger *File // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L80)

	KubeApiserver *File // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L82)

	KubeScheduler *File // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L84)

	KubeControllerManager *File // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L86)

	KwokController *File // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L88)

	MetricsServer *File // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L90)

	Prometheus *File // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L92)
}

func (r *Kwok) Cluster(opts ...KwokClusterOpts) *KwokCluster { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L55)
	q := r.query.Select("cluster")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
		// `components` optional argument
		if !querybuilder.IsZeroValue(opts[i].Components) {
			q = q.Arg("components", opts[i].Components)
		}
		// `controllerPort` optional argument
		if !querybuilder.IsZeroValue(opts[i].ControllerPort) {
			q = q.Arg("controllerPort", opts[i].ControllerPort)
		}
		// `disable` optional argument
		if !querybuilder.IsZeroValue(opts[i].Disable) {
			q = q.Arg("disable", opts[i].Disable)
		}
		// `disableQpslimits` optional argument
		if !querybuilder.IsZeroValue(opts[i].DisableQpslimits) {
			q = q.Arg("disableQpslimits", opts[i].DisableQpslimits)
		}
		// `enable` optional argument
		if !querybuilder.IsZeroValue(opts[i].Enable) {
			q = q.Arg("enable", opts[i].Enable)
		}
		// `enableCrds` optional argument
		if !querybuilder.IsZeroValue(opts[i].EnableCrds) {
			q = q.Arg("enableCrds", opts[i].EnableCrds)
		}
		// `kubeApiserverInsecurePort` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeApiserverInsecurePort) {
			q = q.Arg("kubeApiserverInsecurePort", opts[i].KubeApiserverInsecurePort)
		}
		// `kubeAuditPolicy` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeAuditPolicy) {
			q = q.Arg("kubeAuditPolicy", opts[i].KubeAuditPolicy)
		}
		// `etcd` optional argument
		if !querybuilder.IsZeroValue(opts[i].Etcd) {
			q = q.Arg("etcd", opts[i].Etcd)
		}
		// `jaeger` optional argument
		if !querybuilder.IsZeroValue(opts[i].Jaeger) {
			q = q.Arg("jaeger", opts[i].Jaeger)
		}
		// `kubeApiserver` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeApiserver) {
			q = q.Arg("kubeApiserver", opts[i].KubeApiserver)
		}
		// `kubeScheduler` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeScheduler) {
			q = q.Arg("kubeScheduler", opts[i].KubeScheduler)
		}
		// `kubeControllerManager` optional argument
		if !querybuilder.IsZeroValue(opts[i].KubeControllerManager) {
			q = q.Arg("kubeControllerManager", opts[i].KubeControllerManager)
		}
		// `kwokController` optional argument
		if !querybuilder.IsZeroValue(opts[i].KwokController) {
			q = q.Arg("kwokController", opts[i].KwokController)
		}
		// `metricsServer` optional argument
		if !querybuilder.IsZeroValue(opts[i].MetricsServer) {
			q = q.Arg("metricsServer", opts[i].MetricsServer)
		}
		// `prometheus` optional argument
		if !querybuilder.IsZeroValue(opts[i].Prometheus) {
			q = q.Arg("prometheus", opts[i].Prometheus)
		}
	}

	return &KwokCluster{
		query: q,
	}
}

// A unique identifier for this Kwok.
func (r *Kwok) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Kwok) XXX_GraphQLType() string {
	return "Kwok"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Kwok) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Kwok) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Kwok) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// AsNode returns this Kwok as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Kwok) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

type KwokCluster struct { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L218)
	query *querybuilder.Selection

	id *ID
}

func (r *KwokCluster) WithGraphQLQuery(q *querybuilder.Selection) *KwokCluster {
	return &KwokCluster{
		query: q,
	}
}

func (r *KwokCluster) Container() *Container { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L219)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A unique identifier for this KwokCluster.
func (r *KwokCluster) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *KwokCluster) XXX_GraphQLType() string {
	return "KwokCluster"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *KwokCluster) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *KwokCluster) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *KwokCluster) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// KwokClusterKubeConfigOpts contains options for KwokCluster.KubeConfig
type KwokClusterKubeConfigOpts struct {

	// Default: "kwok"
	Alias string // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L228)
}

func (r *KwokCluster) KubeConfig(opts ...KwokClusterKubeConfigOpts) *File { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L224)
	q := r.query.Select("kubeConfig")
	for i := len(opts) - 1; i >= 0; i-- {
		// `alias` optional argument
		if !querybuilder.IsZeroValue(opts[i].Alias) {
			q = q.Arg("alias", opts[i].Alias)
		}
	}

	return &File{
		query: q,
	}
}

// AsNode returns this KwokCluster as a Node.
// This is a local type conversion — no GraphQL call.
func (r *KwokCluster) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

func (r *Query) Kwok() *Kwok { // kwok (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/kwok/main.go#L16)
	q := r.query.Select("kwok")

	return &Kwok{
		query: q,
	}
}
