// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Release
func (r *Binding) AsRelease() *Release { // release (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/release/main.go#L16)
	q := r.query.Select("asRelease")

	return &Release{
		query: q,
	}
}

// Create or update a binding of type Release in the environment
func (r *Env) WithReleaseInput(name string, value *Release, description string) *Env { // release (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/release/main.go#L16)
	assertNotNil("value", value)
	q := r.query.Select("withReleaseInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Release output to be assigned in the environment
func (r *Env) WithReleaseOutput(name string, description string) *Env { // release (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/release/main.go#L16)
	q := r.query.Select("withReleaseOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Release struct { // release (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/release/main.go#L16)
	query *querybuilder.Selection

	create *Void
	id     *ID
}

func (r *Release) WithGraphQLQuery(q *querybuilder.Selection) *Release {
	return &Release{
		query: q,
	}
}

// ReleaseCreateOpts contains options for Release.Create
type ReleaseCreateOpts struct {
	Cgo bool // release (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/release/main.go#L48)

	// Default: ["linux","darwin"]
	Goos []string // release (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/release/main.go#L53)

	// Default: ["amd64","arm64"]
	Goarch []string // release (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/release/main.go#L58)

	Brew bool // release (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/release/main.go#L60)
}

func (r *Release) Create(ctx context.Context, githubToken *Secret, githubRepo string, name string, opts ...ReleaseCreateOpts) error { // release (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/release/main.go#L42)
	assertNotNil("githubToken", githubToken)
	if r.create != nil {
		return nil
	}
	q := r.query.Select("create")
	for i := len(opts) - 1; i >= 0; i-- {
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `goos` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goos) {
			q = q.Arg("goos", opts[i].Goos)
		}
		// `goarch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goarch) {
			q = q.Arg("goarch", opts[i].Goarch)
		}
		// `brew` optional argument
		if !querybuilder.IsZeroValue(opts[i].Brew) {
			q = q.Arg("brew", opts[i].Brew)
		}
	}
	q = q.Arg("githubToken", githubToken)
	q = q.Arg("githubRepo", githubRepo)
	q = q.Arg("name", name)

	return q.Execute(ctx)
}

// A unique identifier for this Release.
func (r *Release) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Release) XXX_GraphQLType() string {
	return "Release"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Release) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Release) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Release) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// AsNode returns this Release as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Release) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}
