// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Trivy
func (r *Binding) AsTrivy() *Trivy { // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L13)
	q := r.query.Select("asTrivy")

	return &Trivy{
		query: q,
	}
}

// Create or update a binding of type Trivy in the environment
func (r *Env) WithTrivyInput(name string, value *Trivy, description string) *Env { // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L13)
	assertNotNil("value", value)
	q := r.query.Select("withTrivyInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Trivy output to be assigned in the environment
func (r *Env) WithTrivyOutput(name string, description string) *Env { // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L13)
	q := r.query.Select("withTrivyOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// TrivyOpts contains options for Query.Trivy
type TrivyOpts struct {
	Modules *Directory // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L20)

	Container *Container // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L23)
}

// A generated module for Trivy functions
func (r *Query) Trivy(opts ...TrivyOpts) *Trivy { // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L17)
	q := r.query.Select("trivy")
	for i := len(opts) - 1; i >= 0; i-- {
		// `modules` optional argument
		if !querybuilder.IsZeroValue(opts[i].Modules) {
			q = q.Arg("modules", opts[i].Modules)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Trivy{
		query: q,
	}
}

type Trivy struct { // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L13)
	query *querybuilder.Selection

	id    *ID
	image *Void
	repo  *Void
}

func (r *Trivy) WithGraphQLQuery(q *querybuilder.Selection) *Trivy {
	return &Trivy{
		query: q,
	}
}

func (r *Trivy) Container() *Container { // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L14)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Trivy.
func (r *Trivy) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Trivy) XXX_GraphQLType() string {
	return "Trivy"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Trivy) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Trivy) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Trivy) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// TrivyImageOpts contains options for Trivy.Image
type TrivyImageOpts struct {
	DisableTelemtry bool // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L118)

	OfflineScan bool // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L120)

	SkipVersionCheck bool // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L122)

	IgnoreUnfixed bool // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L124)

	EnableModules []string // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L126)

	Severity []string // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L128)

	Scanners []string // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L130)

	IgnoreStatus []string // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L132)
}

func (r *Trivy) Image(ctx context.Context, container *Container, opts ...TrivyImageOpts) error { // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L114)
	assertNotNil("container", container)
	if r.image != nil {
		return nil
	}
	q := r.query.Select("image")
	for i := len(opts) - 1; i >= 0; i-- {
		// `disableTelemtry` optional argument
		if !querybuilder.IsZeroValue(opts[i].DisableTelemtry) {
			q = q.Arg("disableTelemtry", opts[i].DisableTelemtry)
		}
		// `offlineScan` optional argument
		if !querybuilder.IsZeroValue(opts[i].OfflineScan) {
			q = q.Arg("offlineScan", opts[i].OfflineScan)
		}
		// `skipVersionCheck` optional argument
		if !querybuilder.IsZeroValue(opts[i].SkipVersionCheck) {
			q = q.Arg("skipVersionCheck", opts[i].SkipVersionCheck)
		}
		// `ignoreUnfixed` optional argument
		if !querybuilder.IsZeroValue(opts[i].IgnoreUnfixed) {
			q = q.Arg("ignoreUnfixed", opts[i].IgnoreUnfixed)
		}
		// `enableModules` optional argument
		if !querybuilder.IsZeroValue(opts[i].EnableModules) {
			q = q.Arg("enableModules", opts[i].EnableModules)
		}
		// `severity` optional argument
		if !querybuilder.IsZeroValue(opts[i].Severity) {
			q = q.Arg("severity", opts[i].Severity)
		}
		// `scanners` optional argument
		if !querybuilder.IsZeroValue(opts[i].Scanners) {
			q = q.Arg("scanners", opts[i].Scanners)
		}
		// `ignoreStatus` optional argument
		if !querybuilder.IsZeroValue(opts[i].IgnoreStatus) {
			q = q.Arg("ignoreStatus", opts[i].IgnoreStatus)
		}
	}
	q = q.Arg("container", container)

	return q.Execute(ctx)
}

// TrivyRepoOpts contains options for Trivy.Repo
type TrivyRepoOpts struct {
	Workspace *Workspace // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L63)

	// Default: "."
	Path string // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L66)

	DisableTelemtry bool // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L68)

	OfflineScan bool // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L70)

	SkipVersionCheck bool // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L72)

	IgnoreUnfixed bool // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L74)

	EnableModules []string // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L76)

	Severity []string // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L78)

	Scanners []string // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L80)

	IgnoreStatus []string // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L82)
}

func (r *Trivy) Repo(ctx context.Context, opts ...TrivyRepoOpts) error { // trivy (https://github.com/frantjc/daggerverse/tree/6415ad74bf522dc9d89cf4ae9d1e0933affeb66a/trivy/main.go#L61)
	if r.repo != nil {
		return nil
	}
	q := r.query.Select("repo")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `disableTelemtry` optional argument
		if !querybuilder.IsZeroValue(opts[i].DisableTelemtry) {
			q = q.Arg("disableTelemtry", opts[i].DisableTelemtry)
		}
		// `offlineScan` optional argument
		if !querybuilder.IsZeroValue(opts[i].OfflineScan) {
			q = q.Arg("offlineScan", opts[i].OfflineScan)
		}
		// `skipVersionCheck` optional argument
		if !querybuilder.IsZeroValue(opts[i].SkipVersionCheck) {
			q = q.Arg("skipVersionCheck", opts[i].SkipVersionCheck)
		}
		// `ignoreUnfixed` optional argument
		if !querybuilder.IsZeroValue(opts[i].IgnoreUnfixed) {
			q = q.Arg("ignoreUnfixed", opts[i].IgnoreUnfixed)
		}
		// `enableModules` optional argument
		if !querybuilder.IsZeroValue(opts[i].EnableModules) {
			q = q.Arg("enableModules", opts[i].EnableModules)
		}
		// `severity` optional argument
		if !querybuilder.IsZeroValue(opts[i].Severity) {
			q = q.Arg("severity", opts[i].Severity)
		}
		// `scanners` optional argument
		if !querybuilder.IsZeroValue(opts[i].Scanners) {
			q = q.Arg("scanners", opts[i].Scanners)
		}
		// `ignoreStatus` optional argument
		if !querybuilder.IsZeroValue(opts[i].IgnoreStatus) {
			q = q.Arg("ignoreStatus", opts[i].IgnoreStatus)
		}
	}

	return q.Execute(ctx)
}

// AsNode returns this Trivy as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Trivy) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}
