// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Upx
func (r *Binding) AsUpx() *Upx { // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L9)
	q := r.query.Select("asUpx")

	return &Upx{
		query: q,
	}
}

// Create or update a binding of type Upx in the environment
func (r *Env) WithUpxInput(name string, value *Upx, description string) *Env { // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L9)
	assertNotNil("value", value)
	q := r.query.Select("withUpxInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Upx output to be assigned in the environment
func (r *Env) WithUpxOutput(name string, description string) *Env { // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L9)
	q := r.query.Select("withUpxOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// UpxOpts contains options for Query.Upx
type UpxOpts struct {
	Container *Container // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L15)
}

func (r *Query) Upx(opts ...UpxOpts) *Upx { // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L13)
	q := r.query.Select("upx")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Upx{
		query: q,
	}
}

type Upx struct { // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L9)
	query *querybuilder.Selection

	id *ID
}

func (r *Upx) WithGraphQLQuery(q *querybuilder.Selection) *Upx {
	return &Upx{
		query: q,
	}
}

func (r *Upx) Container() *Container { // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L10)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Upx.
func (r *Upx) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Upx) XXX_GraphQLType() string {
	return "Upx"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Upx) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Upx) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Upx) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// UpxPackOpts contains options for Upx.Pack
type UpxPackOpts struct {
	Brute bool // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L32)

	Lzma bool // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L34)
}

func (r *Upx) Pack(executable *File, opts ...UpxPackOpts) *File { // upx (https://github.com/frantjc/daggerverse/tree/fa72b0e77a88b897ad63ab606954e099bea21479/upx/main.go#L28)
	assertNotNil("executable", executable)
	q := r.query.Select("pack")
	for i := len(opts) - 1; i >= 0; i-- {
		// `brute` optional argument
		if !querybuilder.IsZeroValue(opts[i].Brute) {
			q = q.Arg("brute", opts[i].Brute)
		}
		// `lzma` optional argument
		if !querybuilder.IsZeroValue(opts[i].Lzma) {
			q = q.Arg("lzma", opts[i].Lzma)
		}
	}
	q = q.Arg("executable", executable)

	return &File{
		query: q,
	}
}

// AsNode returns this Upx as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Upx) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}
