name: CI
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install_args: dagger
      - name: Set default .env
        run: |
          cat << EOF > .env
          bargeDev_test_githubToken=env://GITHUB_TOKEN
          bargeDev_test_githubRepo=${{ github.repository }}
          bargeDev_test_acrName=${ACR_NAME}
          EOF
      - uses: azure/login@v3
        # This identity only allows federation from main.
        if: github.ref == 'refs/heads/main'
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
      - name: Set azureConfig .env
        if: github.ref == 'refs/heads/main'
        run: echo "bargeDev_test_azureConfig=${AZURE_CONFIG_DIR:-$HOME/.azure}" >> .env
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: dagger check
