name: Release
on:
  push:
    tags:
      # Rough semantic version regexp to only create releases
      # on complete semantic versions e.g. v1.0.0, but not v1.
      - v[0-9]+.[0-9]+.[0-9]+*
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install_args: dagger
      - name: Set github* .env
        run: |
          cat << EOF > .env
          bargeDev_release_githubToken=env://GITHUB_TOKEN
          bargeDev_release_githubRepo=${{ github.repository }}
          EOF
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: dagger call release
